Captain's Log
-------------

The purpose of this file is to log and design forward stuff I am doing and
want to do that is tech-related. The most recent item is below this paragraph
so it's easy to read the latest thing I am working on at the moment.

[[START]]

2014-May-24 | Forget not the push to remote
-------------------------------------------

So I updated git the local repository but forgot to push to origin thereby
breaking the longest streak of 10 days. Things on the present TODO list

  - Update remote with the latest packages
  - Script, using powershell, so compiling and unit testing of scripts happen
  - AsciiDoc plugin for ST2 appears to be broken for
      * URLs not being highlighted
      * List affect colors below the current paragraph



2014-May-23 | AsciiDoc files in Sublime Text 2
----------------------------------------------

Installed https://github.com/SublimeText/AsciiDoc[AsciiDoc plugin for Sublime
Text 2]. This required me to use .asc as the file extension but http://sublimetext.userecho.com/topic/211164-associated-file-extension-to-syntax/[this tip from Sven Axelsson] helped.


2014-May-22 | git going
-----------------------

So I am back to learning Git with all it's attendant problems. I remember learning
it earlier but now I am forced to relearn git so it works with GitHub. Really stoked
that this toybox repository holds a captain's log. 

This file started it's life from a FreeBSD 10.0 Oracle VirtualBox VM running on
Windows 8.1. So today's task was to create this file +captain's_log.asciidoc+ and
upload it to GitHub and correct any errors during the process. 
