Captain's Log
-------------

The purpose of this file is to log and design forward stuff I am doing and
want to do that is tech-related. The most recent item is below this paragraph
so it's easy to read the latest thing I am working on at the moment.

[[START]]

2014-May-25 | ssh-agent and ssh-add at login
--------------------------------------------

Updating +~/.bashrc+ and +~/.bash_profile+ to handle ssh-agent proved trickier
than I expected. I used https://drupal.star.bnl.gov/STAR/blog-entry/jeromel/2009/feb/06/how-safely-start-ssh-agent-bashrc[these great tips
on getting started with ssh-agent]  but for some reason, I could not get
FreeBSD to automatically handle ssh-agent and ssh-add login time. I use tmux
so starting a new tmux window either did not call ssh-agent, or if it did it
called ssh-agent for 'every' tmux window thereby starting new instances of
ssh-agent each time. Finally after many unsuccessful attempts I got it to work
by doing this in my +~/.bash_profile+

[source,sh]
----------------------------------------------------------------------------------------
# Get PID of present ssh-agent and that stored on file
SSH_AGENT_PID=`/usr/bin/tail -1 agent.sh|/usr/bin/cut -d";" -f1|/usr/bin/cut -d"=" -f2`
AGENT_PID=`ps ax|/usr/bin/grep ssh-agent|/usr/bin/grep -v grep|cut -d" " -f1`

# compare, if different it means file version is old, so start ssh-agent
if [ "$AGENT_PID" !=  "$SSH_AGENT_PID" ]; then
  ~/bin/start_ssh-agent
  # ssh-add key-to-add
fi

# call .bashrc for the rest of the stuff
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

----------------------------------------------------------------------------------------

Interesting discussions on http://www.linuxfromscratch.org/blfs/view/6.3/postlfs/profile.html[Bash startup files]


2014-May-24 | Forget not the push to remote
-------------------------------------------

So I updated git the local repository but forgot to push to origin thereby
breaking the present longest streak of 10 days. Things on the present TODO
list

  - Update remote with the latest packages
  - Script, using PowerShell, so compiling and unit testing of scripts happen
  - AsciiDoc plugin for ST2 appears to be broken for
      * URLs not being highlighted
      * List affect colors below the current paragraph
  - Enabled Sublime Text spell checking with F6, using tips from http://robdodson.me/blog/2012/06/23/sublime-text-2-tips-and-shortcuts/[Rob Dodson] 


2014-May-23 | AsciiDoc files in Sublime Text 2
----------------------------------------------

Installed https://github.com/SublimeText/AsciiDoc[AsciiDoc plugin for Sublime
Text 2]. This required me to use .asc as the file extension but http://sublimetext.userecho.com/topic/211164-associated-file-extension-to-syntax/[this tip from Sven Axelsson] helped.


2014-May-22 | git going
-----------------------

So I am back to learning Git with all it's attendant problems. I remember learning
it earlier but now I am forced to relearn git so it works with GitHub. Really stoked
that this toybox repository holds a captain's log. 

This file started it's life from a FreeBSD 10.0 Oracle VirtualBox VM running on
Windows 8.1. So today's task was to create this file +captain's_log.asciidoc+ and
upload it to GitHub and correct any errors during the process. 
