#!/usr/bin/env bash
# --------
# Source: https://drupal.star.bnl.gov/STAR/blog-entry/jeromel/2009/feb/06/how-safely-start-ssh-agent-bashrc

GREP=/usr/bin/grep
#test=`/bin/ps -ef | $GREP ssh-agent | $GREP -v grep | /usr/bin/awk '{print $2}' | xargs`
test=`/bin/ps -ef | $GREP ssh-agent | $GREP -v grep | /usr/bin/awk '{print $2}'`
echo $test

if [ "$test" = "" ]; then

  # there is no agent running
  if [ -e "$HOME/agent.sh" ]; then
    # remove the old file
    /bin/rm -f $HOME/agent.sh
  fi;

  # start a new agent
  /usr/bin/ssh-agent | $GREP -v echo >$HOME/agent.sh

fi;
